# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20160531_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people_model',
            name='vacation',
            field=models.CharField(default=b'none', max_length=100),
        ),
        migrations.AlterField(
            model_name='people_model',
            name='visa',
            field=models.CharField(default=b'none', max_length=100),
        ),
    ]
