# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20160531_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people_model',
            old_name='vacation',
            new_name='vacation_plan',
        ),
        migrations.RenameField(
            model_name='people_model',
            old_name='visa',
            new_name='visa_status',
        ),
        migrations.RemoveField(
            model_name='people_model',
            name='type',
        ),
    ]
