# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20160614_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_model',
            name='Customer_name',
            field=models.CharField(default=b'APJ', max_length=20),
        ),
        migrations.AddField(
            model_name='activity_model',
            name='Description',
            field=models.CharField(default=b'none', max_length=200),
        ),
    ]
