# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20160617_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Allocated', models.CharField(max_length=10)),
            ],
        ),
    ]
