# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_settings_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_model',
            name='Project_Allocated',
            field=models.CharField(default=4, max_length=10),
        ),
    ]
