# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20160721_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings_model',
            name='id',
        ),
        migrations.AddField(
            model_name='settings_model',
            name='Id',
            field=models.AutoField(default='4', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
